"""create terminal_sessions table

Revision ID: f4b05cf0d410
Revises: 
Create Date: 2025-12-18 23:43:16.949271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b05cf0d410'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminal_sessions_id'), 'terminal_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_terminal_sessions_session_id'), 'terminal_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_terminal_sessions_token'), 'terminal_sessions', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terminal_sessions_token'), table_name='terminal_sessions')
    op.drop_index(op.f('ix_terminal_sessions_session_id'), table_name='terminal_sessions')
    op.drop_index(op.f('ix_terminal_sessions_id'), table_name='terminal_sessions')
    op.drop_table('terminal_sessions')
    # ### end Alembic commands ###
